### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by yuliaUU** [STAT547-UBC-2019-20/group05#15]
Amazing readme description! very informative, but one tiny improvement is needed:
- see example hoe to format r code in rmarkdown document, so it is separated from plain text . for example [this link](https://rmarkdown.rstudio.com/authoring_basics.html)

major issue with clean script and EDA:
- not structured (where the `doctop()`?)
- no command line arguments
- does not take in path to the raw data or path where data will be saved
- no function created

**Comment by iciarfernandez** [comment]
Hey Yulia,

Thank you for the feedback! We definitely should've worked more on the scripts, we will add the command line arguments and improve the structure before submitting the next milestone. 

However, we didn't think we needed to create a function according to the milestone instructions (which you mention in your feedback) - could you please clarify this? Also, we have noticed that the grading rubric on Canvas doesn't show up task 3 at all, which was worth 10%. Please let us know!

Thanks again!

**Comment by yuliaUU** [comment]
Hi! Let me check.....
- According to the instructions found [here](https://stat545.stat.ubc.ca/evaluation/milestone_02/milestone_02/) for all tasks it says:
2.2.: "Have at least TWO command-line arguments (at minimum, you may have more as well)
Take in the path to the raw data (in the data folder) as a command-line argument
Take in the filename to where the wrangled data should be saved as a command-line argument"
2.3: "Take in a path where exported images should be saved (likely images) as a command-line argument"
- Demo project: also had it in all of the scripts.
- Lecture Notes: according to section [18.3.3 Structure of scripts](https://stat545guidebook.netlify.com/functional-programming-in-r-part-ii.html) it clearly states what should be inside the scripts

so from what I can gather, there are plenty of indications that you need to use it. But I re-considered your mark for those sections: as I can see you know how to do it from task 2.1 and added points 

Task 3: you are totally right! I added it to the rubric! thanks for catching that .

**Comment by jacobgerlofs** [comment]
Thanks for all your feedback @yuliaUU 
For the sake of Milestone 4, Task 1 (Address peer review feedback), I've quoted below your initial comments and responded to them line-by-line.

I wasn't sure in following the Milestone 4 guidelines if we have to comment on both student peer review and TA comments - the task mentions responding to TA comments. So, for the sake of diligence, we are also responding to your issue!

> Amazing readme description! very informative, but one tiny improvement is needed:
> 
> * see example hoe to format r code in rmarkdown document, so it is separated from plain text . for example [this link](https://rmarkdown.rstudio.com/authoring_basics.html)
> 

Another peer reviewer has also raised this issue. I agree, the code formatting is easier to read/use. We've updated README to use this markdown formatting feature.

> major issue with clean script and EDA:
> 
> * not structured (where the `doctop()`?)
> * no command line arguments
> * does not take in path to the raw data or path where data will be saved
> * no function created

Yes, in working on Milestone 2 we just didn't have time to finish adding all the components of docopt. We figured it was better to have an operating script rather than one that doesn't work while half-implementing docopt and command line arguments. We have since updated all our scripts to use docopt and command line arguments!
