### ISSUE TITLE
Assignment 03 _Peer Review (Farnaz)

### ISSUE THREAD

**Issue by Farnaz1234** [STAT547-UBC-2019-20/group05#33]
Hi Group 5!

- I ran your codes (scripts) on my computer using the commands you suggested and your final reports and plots were correctly generated except for scripts/load.r. Great job! 
- You loaded package readxl although not required, but okay to have it.  
- I learned from your codes that I can use path = here instead of here::here. Thanks!
- I would recommend using read_csv and write_csv since you have loaded the tidyverse package instead of read.csv and write.csv in the base R package.
- You have your repository organized with all required folders ( data, docs, scripts, and images).
- I see usage section in your README.
- The analysis runs pretty quickly.
- I liked your data set and your research question.
- I really liked the geom_point(position = "jitter") you used.
- I believe it is more informative if you label your plots using labs(title= ).
 
Overall, it seems all like a great report with good analysis, well done!

**Comment by jacobgerlofs** [comment]
Thanks @Farnaz1234 for the feedback! I've copied your comments below and addressed them line-by-line

> _Hi Group 5!_

> - _I ran your codes (scripts) on my computer using the commands you suggested and your final reports and plots were correctly generated except for scripts/load.r. Great job!_ 

I'm not sure in which ways load.r was not generated correctly. However, it could be due to not capitalizing the ".R" correctly? In any case, we've now updated the usage section of the read me to have appropriately capitalized command line arguments. I hope this fixes the issue?
 
 

> - _You loaded package readxl although not required, but okay to have it._ 

Yes, functions from this package were used in our load.R script :smiley:


> - _I learned from your codes that I can use path = here instead of here::here. Thanks!_

Glad you learned something yourself! 


> - _I would recommend using read_csv and write_csv since you have loaded the tidyverse package instead of read.csv and write.csv in the base R package._

Good point, it was raised by another peer review that we used these two functions from both packages interchangeably. To be more consistent, we changed the all scripts to use only the tidyverse version of these functions.

> - _You have your repository organized with all required folders ( data, docs, scripts, and images)._
> - _I see usage section in your README._
> - _The analysis runs pretty quickly._
> - _I liked your data set and your research question._
> - _I really liked the geom_point(position = "jitter") you used._

Thanks! :blush:


> - _I believe it is more informative if you label your plots using labs(title= )._

Good point, we've added titles to our ggplots!
